--- W&B initialized ---

--- Initializing Data Loaders (Lazy Loading for GNN) ---
--- Scanning dataset files to build index... ---
Indexing files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 389.92it/s]
--- Scanning dataset files to build index... ---
Indexing files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 373.50it/s]
Total training samples: 38054
Total validation samples: 8078

--- Starting Training from epoch 1 to 5 ---
Epoch 1/5 [TRAIN]:   0%|                                                                                                                                                                        | 0/298 [00:00<?, ?it/s]C:\Users\Arslan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
Epoch 1/5 [TRAIN]:   3%|████                                                                                                                                                 | 8/298 [00:01<00:46,  6.24it/s, loss=1.47]
Traceback (most recent call last):
  File "C:\Users\Arslan\Desktop\MS-Thesis-Oguz-Arslan\containers\ms-thesis-demo\ms-thesis-code\baseline-gnn-hpc.py", line 234, in <module>
    main()
    ~~~~^^
  File "C:\Users\Arslan\Desktop\MS-Thesis-Oguz-Arslan\containers\ms-thesis-demo\ms-thesis-code\baseline-gnn-hpc.py", line 162, in main
    for batch in pbar:
                 ^^^^
  File "C:\Users\Arslan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
               ^^^^^^^^
  File "C:\Users\Arslan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\torch\utils\data\dataloader.py", line 733, in __next__
    data = self._next_data()
  File "C:\Users\Arslan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\torch\utils\data\dataloader.py", line 789, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\Arslan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\torch\utils\data\_utils\fetch.py", line 55, in fetch
    return self.collate_fn(data)
           ~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Arslan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\torch_geometric\loader\dataloader.py", line 27, in __call__
    return Batch.from_data_list(
           ~~~~~~~~~~~~~~~~~~~~^
        batch,
        ^^^^^^
        follow_batch=self.follow_batch,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        exclude_keys=self.exclude_keys,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Arslan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\torch_geometric\data\batch.py", line 97, in from_data_list
    batch, slice_dict, inc_dict = collate(
                                  ~~~~~~~^
        cls,
        ^^^^
    ...<4 lines>...
        exclude_keys=exclude_keys,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Arslan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\torch_geometric\data\collate.py", line 70, in collate
    for store in data.stores:
                 ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'stores'
